name: "Test"
description: "This is a test template, used exclusively for testing!"
id: "com.github.mafelp.test_template"
version: "0.1.0"
author: "MaFeLP <mafelp@proton.me>"
license: "CC0"
tags: ["test"]

files:
  - "index.tex"

sections:
  - name: "General Information"
    description: "General information about the document"
    fields:
      - id: "author"  
        label: "Autor"
        type: "text"
      - id: "title"
        label: "Titel"
        type: "text"
  - name: "Header"
    description: "Header information"
    fields:
      - id: "header_left"
        label: "Header"
        type: "text"
      - id: "header_center"
        label: "Header"
        type: "text"
      - id: "header_right"
        label: "Header"
        type: "text"
