name: release
on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        opt: 
          - os: ubuntu-latest
            name: captura-linux
          - os: windows-latest
            name: captura-windows
          - os: macos-latest
            name: macos-latest

    runs-on: ${{ matrix.opt.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'captura/__main__.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: ${{ matrix.opt.name }}
          options: --onefile, --name "captura", --windowed, --add-data "captura/ui/assets:captura/ui/assets"

