name: release
on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'captura/__main__.py'
          #requirements: 'src/requirements.txt'
          upload_exe_with_name: 'captura'
          options: --onefile, --name "Captura", --windowed,
