name: release
on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install pyinstaller

      - name: Create Application
        run: |
          python -m pyinstaller --name captura --windowed --add-data "captura/ui/assets:assets" captura/__main__.py
          mv dist/captura/ ./captura.app/

      - name: Create .dmg file
        run: |
          create-dmg --volname "Captura" --window-pos 200 120 --window-size 800 450 --icon-size 100 --app-drop-link 600 185 captura.dmg ./captura.app

      - name: Upload .dmg asset
        uses: 'actions/upload-artifact@v4'
        with:
          name: 'captura.dmg'
          path: 'captura.dmg'

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install pyinstaller

      - name: Create Application
        run: |
          python -m pyinstaller --name captura --windowed --add-data "captura/ui/assets:assets" captura/__main__.py
          mv ./dist/captura/ ./captura/

      - name: Create .tar.gz file
        run: |
          tar czf captura.tar.gz ./captura/

      - name: Upload .tar.gz asset
        uses: 'actions/upload-artifact@v4'
        with:
          name: 'captura.tar.gz'
          path: 'captura.tar.gz'

